[project]
name = "app"
version = "0.1.0"
description = "Forgotten Tome Backend"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["fastapi[standard]>=0.115.6", "pydantic>=2.10.3"]

[dependency-groups]
dev = ["pyright>=1.1.406", "ipykernel>=6.29.5", "ruff>=0.14.2"]

[tool.uv]
package = true
