app:
  env: prod
  log_level: INFO
  frontend_url: https://forgottentome.com
  frontend_app_url: https://forgottentome.com/game
  backend_url: https://forgottentome.com
aws:
  region: ap-southeast-1
  s3:
    app_bucket: forgotten-tome-prod
auth:
  google:
    client_id: 929972750529-st0v5go9da8l9u25ioei15ethsiovs9m.apps.googleusercontent.com
    client_secret: {}
    configuration_endpoint: https://accounts.google.com/.well-known/openid-configuration
db:
  hostname: {}
  hostname_unpooled: {}
  name: {}
  port: {}
  username: {}
  password: {}
session:
  signing_key: {}
stripe:
  api_key: {}
  webhook_secret: {}
  pro_product_id: prod_T2w1DT4UKolDZK
  pro_product_price: price_1S6q9XKHEmQHKIEy8oL5z7DD
llm:
  api_key: {}
