"""add llm endpoint

Revision ID: 02c5ad0c45a0
Revises: 71840e3344b1
Create Date: 2025-09-17 22:12:25.329240+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02c5ad0c45a0'
down_revision: Union[str, None] = '71840e3344b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_completion_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_completion'))
    )
    op.create_index(op.f('ix_completion_created_dt'), 'completion', ['created_dt'], unique=False)
    # Drop dependent tables in correct order to satisfy FK constraints
    op.drop_table('feedback')
    op.drop_table('message')
    op.drop_table('chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='fk_feedback_message_id_message'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_feedback_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_feedback'),
    sa.UniqueConstraint('message_id', name='uq_feedback_message_id')
    )
    op.create_table('message',
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('redacted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='fk_message_chat_id_chat'),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], name='fk_message_parent_id_message'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_message_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_message')
    )
    op.create_table('chat',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_chat_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_chat')
    )
    op.drop_index(op.f('ix_completion_created_dt'), table_name='completion')
    op.drop_table('completion')
    # ### end Alembic commands ###
