"""rename created_by on Story

Revision ID: 1f4c725e06e7
Revises: 3535d90e2714
Create Date: 2025-10-24 16:59:13.963807+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4c725e06e7'
down_revision: Union[str, None] = '3535d90e2714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'created_by', new_column_name='user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'user_id', new_column_name='created_by')
    # ### end Alembic commands ###
