"""add emails

Revision ID: 20cb2a2e5707
Revises: c2d5fb90b0e2
Create Date: 2025-09-21 15:19:16.165373+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20cb2a2e5707'
down_revision: Union[str, None] = 'c2d5fb90b0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email')),
    sa.UniqueConstraint('email', name=op.f('uq_email_email'))
    )
    op.drop_index('ix_feedback_created_dt', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_chat_created_dt', table_name='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_created_dt', 'chat', ['created_dt'], unique=False)
    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_feedback_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_feedback')
    )
    op.create_index('ix_feedback_created_dt', 'feedback', ['created_dt'], unique=False)
    op.drop_table('email')
    # ### end Alembic commands ###
