"""set null lorestone

Revision ID: 3535d90e2714
Revises: b072463a0881
Create Date: 2025-10-16 22:24:59.376045+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3535d90e2714'
down_revision: Union[str, None] = 'b072463a0881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_lorestone_transaction_message_id_message'), 'lorestone_transaction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lorestone_transaction_message_id_message'), 'lorestone_transaction', 'message', ['message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_lorestone_transaction_message_id_message'), 'lorestone_transaction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lorestone_transaction_message_id_message'), 'lorestone_transaction', 'message', ['message_id'], ['id'])
    # ### end Alembic commands ###
