"""add lorestones, story

Revision ID: 549b2a8e2838
Revises: 20cb2a2e5707
Create Date: 2025-10-02 15:31:26.612186+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549b2a8e2838'
down_revision: Union[str, None] = '20cb2a2e5707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre')),
    sa.UniqueConstraint('name', name=op.f('uq_genre_name'))
    )
    op.create_table('story',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_story_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story'))
    )
    op.create_index(op.f('ix_story_created_at'), 'story', ['created_at'], unique=False)
    op.create_table('genre_story',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_genre_story_genre_id_genre'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_genre_story_story_id_story'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'genre_id', name=op.f('pk_genre_story'))
    )
    op.create_table('message',
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', native_enum=False), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_message_chat_id_chat')),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], name=op.f('fk_message_parent_id_message')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_message_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_table('lorestone_transaction',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance_before_transaction', sa.Integer(), nullable=False),
    sa.Column('balance_after_transaction', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('new_user_bonus', 'daily_bonus', 'purchase', 'admin_adjustment', 'story_generation', native_enum=False), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_lorestone_transaction_message_id_message')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lorestone_transaction_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lorestone_transaction'))
    )
    op.create_index(op.f('ix_lorestone_transaction_created_at'), 'lorestone_transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_lorestone_transaction_message_id'), 'lorestone_transaction', ['message_id'], unique=False)
    op.create_index(op.f('ix_lorestone_transaction_user_id'), 'lorestone_transaction', ['user_id'], unique=False)
    op.drop_index('ix_completion_created_dt', table_name='completion')
    op.drop_table('completion')
    op.add_column('chat', sa.Column('story_id', sa.Uuid(), nullable=False))
    op.add_column('chat', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat', sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', 'not_started', native_enum=False), nullable=False))
    op.add_column('chat', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_chat_status'), 'chat', ['status'], unique=False)
    op.create_index(op.f('ix_chat_updated_at'), 'chat', ['updated_at'], unique=False)
    op.create_foreign_key(op.f('fk_chat_story_id_story'), 'chat', 'story', ['story_id'], ['id'])
    op.drop_column('chat', 'title')
    op.drop_column('chat', 'created_dt')
    op.add_column('error', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('error', 'created_dt')
    op.add_column('subscription', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('subscription', 'created_dt')
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('uq_user_sub', 'user', type_='unique')
    op.create_index(op.f('ix_user_sub'), 'user', ['sub'], unique=True)
    op.drop_column('user', 'created_dt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_sub'), table_name='user')
    op.create_unique_constraint('uq_user_sub', 'user', ['sub'])
    op.drop_column('user', 'created_at')
    op.add_column('subscription', sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('subscription', 'created_at')
    op.add_column('error', sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('error', 'created_at')
    op.add_column('chat', sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_chat_story_id_story'), 'chat', type_='foreignkey')
    op.drop_index(op.f('ix_chat_updated_at'), table_name='chat')
    op.drop_index(op.f('ix_chat_status'), table_name='chat')
    op.drop_column('chat', 'created_at')
    op.drop_column('chat', 'status')
    op.drop_column('chat', 'updated_at')
    op.drop_column('chat', 'story_id')
    op.create_table('completion',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_completion_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_completion')
    )
    op.create_index('ix_completion_created_dt', 'completion', ['created_dt'], unique=False)
    op.drop_index(op.f('ix_lorestone_transaction_user_id'), table_name='lorestone_transaction')
    op.drop_index(op.f('ix_lorestone_transaction_message_id'), table_name='lorestone_transaction')
    op.drop_index(op.f('ix_lorestone_transaction_created_at'), table_name='lorestone_transaction')
    op.drop_table('lorestone_transaction')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_table('message')
    op.drop_table('genre_story')
    op.drop_index(op.f('ix_story_created_at'), table_name='story')
    op.drop_table('story')
    op.drop_table('genre')
    # ### end Alembic commands ###
