"""initial

Revision ID: 71840e3344b1
Revises:
Create Date: 2025-09-05 20:28:32.598259+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71840e3344b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('source', sa.Enum('frontend', 'backend', native_enum=False), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error'))
    )
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'email', native_enum=False), nullable=False),
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('provider', 'sub', name='uq_user_provider_sub'),
    sa.UniqueConstraint('sub', name=op.f('uq_user_sub'))
    )
    op.create_table('chat',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat'))
    )
    op.create_table('subscription',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('product', sa.Enum('pro', native_enum=False), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_subscription_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription')),
    sa.UniqueConstraint('user_id', deferrable=True, initially='DEFERRED', name=op.f('uq_subscription_user_id'))
    )
    op.create_table('message',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_message_chat_id_chat')),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], name=op.f('fk_message_parent_id_message')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_message_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_feedback_message_id_message')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_feedback_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('message_id', name=op.f('uq_feedback_message_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('message')
    op.drop_table('subscription')
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('error')
    # ### end Alembic commands ###
