"""cascade delete messages

Revision ID: b072463a0881
Revises: 9ccb3edfd2d6
Create Date: 2025-10-16 22:23:38.574506+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b072463a0881'
down_revision: Union[str, None] = '9ccb3edfd2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_message_chat_id_chat'), 'message', type_='foreignkey')
    op.create_foreign_key(op.f('fk_message_chat_id_chat'), 'message', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_message_chat_id_chat'), 'message', type_='foreignkey')
    op.create_foreign_key(op.f('fk_message_chat_id_chat'), 'message', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###
