"""add deleted_at to story

Revision ID: b37ad6b9453b
Revises: 1f4c725e06e7
Create Date: 2025-10-31 16:11:31.153401+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37ad6b9453b'
down_revision: Union[str, None] = '1f4c725e06e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_story_deleted_at'), 'story', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_deleted_at'), table_name='story')
    op.drop_column('story', 'deleted_at')
    # ### end Alembic commands ###
